plugins {
    id 'java'
    id 'war'
}

war {
    archiveBaseName = 'thuctap'
}

group = 'vn.edu.nlu.fit'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.1'
    implementation 'org.jdbi:jdbi3-core:3.50.0'
    implementation 'com.mysql:mysql-connector-j:9.3.0'
    implementation 'com.sun.mail:jakarta.mail:2.0.1'
    implementation 'org.mindrot:jbcrypt:0.4'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
