db.host=localhost
db.port=3306
db.username=root
db.password=
db.dbName=project
db.dbOption=
ghn.base_url=https://online-gateway.ghn.vn/shiip/public-api
ghn.token=51c150f3-5f43-11f1-8b97-6a86b59a8474
ghn.shop_id=6471522
ghn.from_district_id=3695
ghn.from_ward_code=90737
ghn.service_id=53320
