db.host=localhost
db.port=3306
db.username=root
db.password=
db.dbName=project
db.dbOption=
ghn.base_url=https://online-gateway.ghn.vn/shiip/public-api
ghn.mode=simulation
ghn.token=
ghn.shop_id=
ghn.from_district_id=
ghn.from_ward_code=
ghn.service_id=
ghn.from_name=Handmade House
ghn.from_phone=
ghn.from_address=
ghn.from_ward_name=
ghn.from_district_name=
ghn.from_province_name=
